### ISSUE TITLE
Is Thinkpad keyboard TrackPoint regarded as a key？

### ISSUE THREAD

**Issue by supermice** [BillBillBillBill/Tickeys-linux#10]
Hi，guys. The Tickeys sounds really cool.
However, when i use my thinkpad keyboard which equipped with a TrackPoint, tickeys seems regard the operation of the TrackPoint as a key press action and makes a sound constantly. Can i fix this by editing configuration files ?
My operation system is ubuntu 1404 LTS, with the kernel of 4.4.0-040400-generic.

**Comment by BillBillBillBill** [comment]
Thank you for reporting this, apperently this is a bug, I will fix it in the next version if I got time:)

**Comment by BillBillBillBill** [comment]
fix
