### ISSUE TITLE
找不到音频设备 ubuntu 

### ISSUE THREAD

**Issue by royaso** [BillBillBillBill/Tickeys-linux#3]
pygame.error: No available audio device

pip install

**Comment by BillBillBillBill** [comment]
重启试试(认真)?

**Comment by royaso** [comment]
@BillBillBillBill 好,试试看(ps,回复好快,pps: readme有个笔误

然后使用cx_freeze进行打包：sudo python bulid.py bulid

**Comment by royaso** [comment]
@BillBillBillBill 

## 本想大呼"重启大法好"没想到.....

Home directory not accessible: Permission denied
Home directory not accessible: Permission denied
ALSA lib pcm_hw.c:1667:(_snd_pcm_hw_open) Invalid value for card
Run GUI Fail, use CLI instead..Fail msg:No available audio device
Root checking...
Root checking success..
Home directory not accessible: Permission denied
ALSA lib pcm_hw.c:1667:(_snd_pcm_hw_open) Invalid value for card
Traceback (most recent call last):
  File "/usr/local/bin/tickeys", line 9, in <module>
    load_entry_point('tickeys==0.1.5', 'console_scripts', 'tickeys')()
  File "/usr/local/lib/python2.7/dist-packages/tickeys/run.py", line 48, in run
    run_GUI()
  File "/usr/local/lib/python2.7/dist-packages/tickeys/run.py", line 22, in run_GUI
    run_CLI()
  File "/usr/local/lib/python2.7/dist-packages/tickeys/run.py", line 28, in run_CLI
    CLI().cmdloop()
  File "/usr/local/lib/python2.7/dist-packages/tickeys/CLI.py", line 19, in __init__
    self.detecter = KeyboardHandler()
  File "/usr/local/lib/python2.7/dist-packages/tickeys/KeyboardHandler.py", line 26, in **init**
    self.sp = SoundPlayer()
  File "/usr/local/lib/python2.7/dist-packages/tickeys/SoundPlayer.py", line 20, in **init**
    self.mixer.init(frequency=22050)
pygame.error: No available audio device

**Comment by BillBillBillBill** [comment]
@royaso 啊- -奇怪,见过这个问题,一般是重启就好了...提示Permission denied额,有没有用root权限运行?

**Comment by royaso** [comment]
@BillBillBillBill
 $  tickeys -g 
Root checking...
This program must be run as root..

这是没sudo的样子

**Comment by BillBillBillBill** [comment]
@royaso 
神奇啦- -试试这个?
sudo apt-get install libsdl1.2debian:i386

**Comment by royaso** [comment]
@BillBillBillBill 
正在读取软件包列表... 完成
正在分析软件包的依赖关系树  
正在读取状态信息... 完成  
libsdl1.2debian 已经是最新的版本了。
libsdl1.2debian 被设置为手动安装。
升级了 0 个软件包，新安装了 0 个软件包，要卸载 0 个软件包，有 806 个软件包未被升级。

**Comment by BillBillBillBill** [comment]
@royaso 
- -看看这些都有不? 

sudo apt-get install libsdl1.2-dev
sudo apt-get install libsdl-mixer1.2
sudo apt-get install libsdl-ttf2.0

还不行的话参考下面说的？
http://forums.libsdl.org/viewtopic.php?t=7609
https://kdenlive.org/forum/sdl-failed-open-audio-no-available-audio-device

**Comment by royaso** [comment]
@BillBillBillBill 

早先见过类似的软件,那时候我还在用xp

所以没想到ubuntu下也能有类似的,就兴冲冲安装,没想到不行,你readme各种可能和依赖什么的都试过了,还追到了你主站和pypi,甚至都想自己编译(虽然不太懂)

我还是放弃了,可能真是rp问题,有机会在别的电脑上试试

**Comment by BillBillBillBill** [comment]
@royaso 
那就不好意思了哈- -
这软件有windows版的

**Comment by royaso** [comment]
@BillBillBillBill 
恩,知道,原先是mac版,然后windows,再然后才linux

玩linux的也应该明白了,因为玩的是linux

**Comment by royaso** [comment]
无意间发现,用另外的用户就可以了!
