### ISSUE TITLE
Ubuntu 15.10 12月3号更新补丁后无声音

### ISSUE THREAD

**Issue by aesean** [BillBillBillBill/Tickeys-linux#8]
Ubuntu 15.10 X64 12月3号更新补丁后无声音。更新之前是好好的，安装方式是pip。
sudo tickeys 启动正常，无报错。终端自动消失后，键盘无声音。系统用播放器播放声音文件正常。

uname -a
Linux linux-pc 4.2.0-19-generic #23-Ubuntu SMP Wed Nov 11 11:39:30 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux

**Comment by BillBillBillBill** [comment]
你好,可以贴一下在/tmp/tickeys.log的内容吗

**Comment by aesean** [comment]
test  -logger.py[line:29]
Tickeys start........  -run.py[line:69]
Root checking...  -run.py[line:38]
Root checking success..  -run.py[line:42]
File path:/usr/local/lib/python2.7/dist-packages/tickeys  -run.py[line:43]
Version checking...  -run.py[line:48]
It is the latest version...  -run.py[line:53]
Keyboard deteccter created.  -KeyboardHandler.py[line:21]
Load sound file:./Resources/data/Cherry_G80_3000/G80-3000.wav  -SoundPlayer.py[line:43]
Load sound file:./Resources/data/Cherry_G80_3000/G80-3000_fast1.wav  -SoundPlayer.py[line:43]
Load sound file:./Resources/data/Cherry_G80_3000/G80-3000_slow1.wav  -SoundPlayer.py[line:43]
Load sound file:./Resources/data/Cherry_G80_3000/G80-3000_fast2.wav  -SoundPlayer.py[line:43]
Load sound file:./Resources/data/Cherry_G80_3000/G80-3000_slow2.wav  -SoundPlayer.py[line:43]
Load sound file:./Resources/data/Cherry_G80_3000/G80-3000.wav  -SoundPlayer.py[line:43]
Load sound file:./Resources/data/Cherry_G80_3000/G80-3000_fast1.wav  -SoundPlayer.py[line:43]
Load sound file:./Resources/data/Cherry_G80_3000/G80-3000_slow1.wav  -SoundPlayer.py[line:43]
Load sound file:./Resources/data/Cherry_G80_3000/G80-3000_fast2.wav  -SoundPlayer.py[line:43]
Load sound file:./Resources/data/Cherry_G80_3000/G80-3000_slow2.wav  -SoundPlayer.py[line:43]
List all device  -KeyboardHandler.py[line:33]
Name: event10 Device: Integrated_Webcam_HD
  -KeyboardHandler.py[line:37]
Name: event11 Device: HDA Intel HDMI HDMI/DP,pcm=3
  -KeyboardHandler.py[line:37]
Name: event12 Device: HDA Intel HDMI HDMI/DP,pcm=7
  -KeyboardHandler.py[line:37]
Name: event13 Device: HDA Intel HDMI HDMI/DP,pcm=8
  -KeyboardHandler.py[line:37]
Name: event14 Device: Dell WMI hotkeys
  -KeyboardHandler.py[line:37]
Name: event15 Device: HDA Intel PCH Headphone Mic
  -KeyboardHandler.py[line:37]
Name: event0 Device: Power Button
  -KeyboardHandler.py[line:37]
Name: event1 Device: Sleep Button
  -KeyboardHandler.py[line:37]
Name: event2 Device: Lid Switch
  -KeyboardHandler.py[line:37]
Name: event3 Device: Power Button
  -KeyboardHandler.py[line:37]
Name: event4 Device: AT Translated Set 2 keyboard
  -KeyboardHandler.py[line:37]
Name: event5 Device: Video Bus
  -KeyboardHandler.py[line:37]
Name: event6 Device: Video Bus
  -KeyboardHandler.py[line:37]
Name: event7 Device: Logitech USB-PS/2 Optical Mouse
  -KeyboardHandler.py[line:37]
Name: event8 Device: SynPS/2 Synaptics TouchPad
  -KeyboardHandler.py[line:37]
Name: event9 Device: DELL Wireless hotkeys
  -KeyboardHandler.py[line:37]
Name: mouse0 Device: Logitech USB-PS/2 Optical Mouse
  -KeyboardHandler.py[line:37]
Name: mouse1 Device: SynPS/2 Synaptics TouchPad
  -KeyboardHandler.py[line:37]
Key: 32 Status: pressed  -KeyboardHandler.py[line:117]
Key: 32 Status: release  -KeyboardHandler.py[line:117]
Key: 32 Status: pressed  -KeyboardHandler.py[line:117]
Key: 32 Status: release  -KeyboardHandler.py[line:117]
Key: 32 Status: pressed  -KeyboardHandler.py[line:117]
Key: 32 Status: release  -KeyboardHandler.py[line:117]
Key: 32 Status: pressed  -KeyboardHandler.py[line:117]

**Comment by aesean** [comment]
日志很长，后面没贴的都是
Key: *\* Status: release -KeyboardHandler.py[line:117]
Key: *\* Status: pressed -KeyboardHandler.py[line:117]
的重复内容。**为数字。

**Comment by BillBillBillBill** [comment]
看起来启动和运行都是正常了，更新系统后不行可能是所依赖的某些库有问题呢。。。

**Comment by aesean** [comment]
最新有发现，没有声音是间歇性的，我刚sudo tickeys，然后声音又正常了，过了5分钟。浏览了几个网页，然后快捷键Ctrl W关闭网页标签的时候发现又没声音了。真的太喜欢这个软件了，不知道我有没有什么方法能帮忙debug的。

**Comment by BillBillBillBill** [comment]
- -这么神奇,你是怎么安装的?启动后能正常唤出吧?是之前一直正常然后系统更新就不行了吗?

**Comment by aesean** [comment]
安装是pip install，3号更新补丁前是完全正常的，3号更新了一大堆补丁后就开始不正常了。现在是有时候可以有时候不可以，这个先不管了，我不知道是不是我本地环境哪里有不正常。

然后一个问题是声音有个比较明显的延迟的，不知道这个能不能通过参数调整。
再一个就是声音特别小，这个不知道能不能单独设置声音大小。

**Comment by BillBillBillBill** [comment]
明明就有设置声音大小和音调高低的选项嘛.....

**Comment by aesean** [comment]
原因我找到了，是Tickeys的进程被杀死导致的。具体为什么被杀死还没找到原因。声音选项确实有，我的问题，我没注意QAZ123。感谢作者。

**Comment by aesean** [comment]
原因这次是真的发现了，不是进程被杀死了。是触控板操作的时候会有BUG。我不太清楚是不是只有我的电脑会这样。我电脑是DELL 灵越7000游匣。只要是拔掉鼠标用触控板就会出问题，而且在没有鼠标的时候QAZ123，打开GUI界面进度条和下拉菜单就开始不听话了，完全没办法正常设置。

**Comment by BillBillBillBill** [comment]
你好 方便的话加下我QQ:536803427

**Comment by aesean** [comment]
暂时放弃了GUI版本。
